export const paths = {
	clientHome: '/client/homepage',
	vetHome: '/vet/homepage',
	vetsubmitDet: '/vet/completeRegistration',
	ratings: '/client/ratings',
	request: '/client/requestVet',
	details: '/client/ratings/details',
	requestTimeline: '/client/timeline',
	historyReview: '/client/review',
	clientReset: '/client/reset-password',
	vetReset: '/vet/reset-password',
	rootLogin: '/auth/log-in/client',
	vetLogin: '/auth/log-in/vet',
	signUp: '/auth/sign-up',
	notFound: '/*',
};

export const remoteuri = {
	addtoPull: '/vet/add-to-pull',
	removeFromPool: '/vet/remove-from-pull',
	jobPrice: '/vet/set-job-price',
	viewJobs: '/vet/view-all-jobs',
	viewRecomm: '/vet/recommended-jobs',
	addVetDet: '/vet/edit-details',
	getPool: '/vet/job-pool',
	ROOT_URL: 'http://localhost:3000',
	postJob: '/client/post-job',
	allforClient: '/client/all-jobs',
	reviewJob: '/client/review-job',
};
